---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: growi-canfes-up-files
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: y-canfes
    name: wiki-up-files
  nfs:
    server: nfs.unipro.infra
    path: /nfs/users/yuito-it/canfes/wiki/uploaded_files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-up-files
  labels:
    app: growi
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: growi-canfes-up-files
