---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: growi-canfes-app
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: growi
    name: data
  nfs:
    server: nfs.unipro.infra
    path: /nfs/users/yuito-it/canfes/growi/app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  labels:
    app: growi
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: growi-canfes-app
